// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aocvodsfarlzipejibou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvY3ZvZHNmYXJsemlwZWppYm91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDI2OTYsImV4cCI6MjA2NTY3ODY5Nn0.lnLOu3HURkxTi-Kv0191CGX3QAIZn_E3nevO8cVCKs0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);